float instead of int for cjfee
A poorly coded or malicious maker bot script may be able to cause all potential takers to hang when seeking available orders, with something like

    ValueError: invalid literal for int() with base 10: '0.1337'

This is done by making certain changes to how the maker order is announced to potential takers in IRC.

Change int to float instead possibly to avoid hanging?  Not sure what else this may affect or if this is the best solution, in any case, but this is a potential way to deny service to takers, so please review ASAP.